# Generated by Django 3.0.2 on 2020-03-31 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
