# Generated by Django 3.0.2 on 2020-04-11 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cwapi', '0006_item_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A&C', 'Antiques & Collectibles'), ('AUT', 'Automotive'), ('BOK', 'Books'), ('C&A', 'Clothing & Accessories'), ('E&C', 'Electronics & Computers'), ('H&G', 'Home & Garden'), ('JEW', 'Jewellery'), ('L&T', 'Luggage & Travel'), ('MUS', 'Musical Instruments'), ('OFF', 'Office Products'), ('S&V', 'Software & Videogames'), ('T&E', 'Tools & Equipment'), ('TOY', 'Toys')], max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
