# Generated by Django 3.0.2 on 2020-04-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0007_auto_20200411_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.CharField(max_length=25),
        ),
    ]
