# Generated by Django 3.0.2 on 2020-04-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0009_auction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='item_id',
        ),
        migrations.AddField(
            model_name='auction',
            name='item_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cwapi.Item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='time_left',
            field=models.DurationField(verbose_name='Time left to complete'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A&C', 'Antiques & Collectibles'), ('AUT', 'Automotive'), ('BOK', 'Books'), ('C&A', 'Clothing & Accessories'), ('E&C', 'Electronics & Computers'), ('H&G', 'Home & Garden'), ('JEW', 'Jewellery'), ('L&T', 'Luggage & Travel'), ('MUS', 'Musical Instruments'), ('OFF', 'Office Products'), ('S&V', 'Software & Videogames'), ('T&E', 'Tools & Equipment'), ('TOY', 'Toys')], max_length=3, verbose_name='Item Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('N', 'New'), ('U', 'Used')], max_length=1, verbose_name='Condition of the Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Item identifier'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_title',
            field=models.CharField(max_length=100, verbose_name='Item Title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
    ]
