# Generated by Django 3.0.2 on 2020-04-13 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0011_auto_20200412_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_id',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='time_left',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
        migrations.AddField(
            model_name='auction',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='item_title',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cwapi.Item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Starting Price'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidder', models.CharField(max_length=25)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Bid')),
                ('bid_timestamp', models.DateTimeField(auto_now_add=True)),
                ('item_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwapi.Item')),
            ],
        ),
    ]
