# Generated by Django 3.0.2 on 2020-04-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0012_auto_20200413_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_status',
            field=models.CharField(default=123, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_winer',
            field=models.CharField(default=1234, max_length=25),
            preserve_default=False,
        ),
    ]
