# Generated by Django 3.0.2 on 2020-04-13 03:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0013_auto_20200413_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_amount',
            new_name='bid_price',
        ),
        migrations.AddField(
            model_name='item',
            name='time_left',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time left to complete'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Item Description'),
        ),
    ]
