# Generated by Django 3.0.2 on 2020-04-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0014_auto_20200413_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time_left',
            field=models.IntegerField(blank=True, verbose_name='Days to complete'),
        ),
    ]
