# Generated by Django 3.0.2 on 2020-04-13 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0016_auto_20200413_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time_left',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 13, 14, 40, 41, 810473)),
        ),
    ]
