# Generated by Django 3.0.2 on 2020-04-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0017_auto_20200413_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time_left',
            field=models.CharField(max_length=25),
        ),
    ]
