# Generated by Django 3.0.2 on 2020-04-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0018_auto_20200413_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='time_left',
        ),
    ]
