# Generated by Django 3.0.2 on 2020-04-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0019_remove_item_time_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='expiry_date',
            new_name='expiration_timedate',
        ),
    ]
