# Generated by Django 3.0.2 on 2020-04-13 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0022_auto_20200413_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='item_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cwapi.Item'),
        ),
    ]
