# Generated by Django 3.0.2 on 2020-04-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0023_auto_20200413_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='item_title',
            new_name='item',
        ),
    ]
