# Generated by Django 3.0.2 on 2020-04-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0024_auto_20200413_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={},
        ),
        migrations.RemoveField(
            model_name='auction',
            name='auction_status',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='auction_winer',
        ),
    ]
