# Generated by Django 3.0.2 on 2020-04-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0025_auto_20200413_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='item',
            new_name='item_title',
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_status',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
