# Generated by Django 3.0.2 on 2020-04-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0026_auto_20200413_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_status',
        ),
    ]
