# Generated by Django 3.0.2 on 2020-04-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0028_auction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Closed'), (1, 'Active')], default=1),
        ),
    ]
