# Generated by Django 3.0.2 on 2020-04-14 02:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0029_auto_20200413_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_title']},
        ),
        migrations.RemoveField(
            model_name='auction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='expiration_timedate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='posted_timedate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='item',
            name='starting_price',
        ),
        migrations.AddField(
            model_name='auction',
            name='expiration_timedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='posted_timedate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='seller',
            field=models.CharField(default='Manuel', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Starting Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='item_title',
            field=models.CharField(max_length=100, verbose_name='Item Title'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cwapi.Item'),
        ),
    ]
