# Generated by Django 3.0.2 on 2020-04-14 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0030_auto_20200414_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'ordering': ['-posted_timedate']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterField(
            model_name='bid',
            name='item_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwapi.Auction'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cwapi.Auction'),
        ),
    ]
