# Generated by Django 3.0.2 on 2020-04-14 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0031_auto_20200414_0227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemDetail',
        ),
    ]
