# Generated by Django 3.0.2 on 2020-04-15 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0035_auto_20200415_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='item_title',
            new_name='item',
        ),
    ]
