# Generated by Django 3.0.2 on 2020-04-15 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0036_auto_20200415_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='item',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='item_name',
        ),
    ]
