# Generated by Django 3.0.2 on 2020-04-15 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0037_auto_20200415_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A&C', 'Antiques & Collectibles'), ('AUT', 'Automotive'), ('BOK', 'Books'), ('C&A', 'Clothing & Accessories'), ('E&C', 'Electronics & Computers'), ('H&G', 'Home & Garden'), ('JEW', 'Jewellery'), ('L&T', 'Luggage & Travel'), ('MUS', 'Musical Instruments'), ('OFF', 'Office Products'), ('S&V', 'Software & Videogames'), ('T&E', 'Tools & Equipment'), ('TOY', 'Toys')], max_length=3, verbose_name='Item Category')),
                ('condition', models.CharField(choices=[('N', 'New'), ('U', 'Used')], max_length=1, verbose_name='Condition of the Item')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('description', models.TextField(verbose_name='Item Description')),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='ask_price',
            field=models.PositiveIntegerField(verbose_name='Starting Price'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='item_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cwapi.Auction'),
        ),
    ]
