# Generated by Django 3.0.2 on 2020-04-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0038_auto_20200415_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='item_title',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='itemdetail',
            old_name='item_name',
            new_name='item_id',
        ),
    ]
