# Generated by Django 3.0.2 on 2020-04-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0039_auto_20200415_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdetail',
            old_name='item_id',
            new_name='auction_id',
        ),
    ]
