# Generated by Django 3.0.2 on 2020-04-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0040_auto_20200415_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemdetail',
            old_name='category',
            new_name='item_category',
        ),
        migrations.RenameField(
            model_name='itemdetail',
            old_name='condition',
            new_name='item_condition',
        ),
        migrations.RenameField(
            model_name='itemdetail',
            old_name='description',
            new_name='item_description',
        ),
        migrations.RenameField(
            model_name='itemdetail',
            old_name='quantity',
            new_name='item_quantity',
        ),
    ]
