# Generated by Django 3.0.2 on 2020-04-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0041_auto_20200415_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Closed'), (1, 'Active')], default=1),
        ),
    ]
