# Generated by Django 3.0.2 on 2020-04-15 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0044_auction_auction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='auction_status',
        ),
    ]
