# Generated by Django 3.0.2 on 2020-04-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0045_remove_auction_auction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
