# Generated by Django 3.0.2 on 2020-04-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0046_auction_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='is_active',
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_status',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
