# Generated by Django 3.0.2 on 2020-04-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0047_auto_20200415_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_status',
            field=models.CharField(default='Open to offers', max_length=15),
        ),
    ]
