# Generated by Django 3.0.2 on 2020-04-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0049_auto_20200416_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_winner',
            field=models.CharField(default='To be confirmed', max_length=25),
        ),
        migrations.AlterField(
            model_name='auction',
            name='ask_price',
            field=models.PositiveIntegerField(verbose_name='Starting Price (£)'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_status',
            field=models.CharField(default='Open to offers', max_length=25),
        ),
    ]
