# Generated by Django 3.0.2 on 2020-04-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0052_auto_20200417_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='item_id',
            new_name='auction_id',
        ),
    ]
