# Generated by Django 3.0.2 on 2020-04-17 20:37

import cwapi.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0053_auto_20200417_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetail',
            name='id',
        ),
        migrations.AddField(
            model_name='auction',
            name='bidder',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_status',
            field=models.CharField(default='Open to offers', editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auction_winner',
            field=models.CharField(default='To be confirmed', max_length=25),
        ),
        migrations.AlterField(
            model_name='auction',
            name='expiration_timedate',
            field=models.DateTimeField(validators=[cwapi.models.Auction.is_in_the_future]),
        ),
        migrations.AlterField(
            model_name='auction',
            name='item_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Item Title'),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='auction_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='items', serialize=False, to='cwapi.Auction'),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='item_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='item_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
