# Generated by Django 2.2.12 on 2020-04-19 03:44

import cwapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0054_auto_20200419_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, validators=[cwapi.models.Auction.is_positive], verbose_name='Purchase Price (£)'),
        ),
    ]
