# Generated by Django 3.0.2 on 2020-04-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0054_auto_20200417_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetail',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='auction_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cwapi.Auction'),
        ),
    ]
