# Generated by Django 3.0.2 on 2020-04-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwapi', '0057_bid_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='owner',
        ),
    ]
